{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handlePanGestureForRightView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"gesture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPanGestureRecognizer","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/slsidemenu\/slsidemenu\/handlepangestureforrightview(gesture:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/slsidemenu\/slsidemenu\/handlepangestureforrightview(gesture:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/handlePanGestureForRightView(gesture:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handlePanGestureForRightView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"gesture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPanGestureRecognizer","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer"},{"kind":"text","text":")"}],"title":"handlePanGestureForRightView(gesture:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@SLSideMenu@objc(cs)SLSideMenu(im)handlePanGestureForRightViewWithGesture:","modules":[{"name":"SLSideMenu"}],"navigatorTitle":[{"kind":"identifier","text":"handlePanGestureForRightViewWithGesture:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu"]]},"references":{"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu":{"role":"symbol","title":"SLSideMenu","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenu"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenu"}],"url":"\/documentation\/slsidemenu\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu/handlePanGestureForRightView(gesture:)":{"role":"symbol","title":"handlePanGestureForRightView(gesture:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handlePanGestureForRightView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"gesture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPanGestureRecognizer","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/handlePanGestureForRightView(gesture:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"handlePanGestureForRightViewWithGesture:"}],"url":"\/documentation\/slsidemenu\/slsidemenu\/handlepangestureforrightview(gesture:)"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu":{"role":"collection","title":"SLSideMenu","abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"handlePanGestureForRightViewWithGesture:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handlePanGestureForRightViewWithGesture:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"handlePanGestureForRightViewWithGesture:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPanGestureRecognizer","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"gesture"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/title","value":"SLSideMenu"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/fragments","value":[{"kind":"identifier","text":"SLSideMenu"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1handlePanGestureForRightView(gesture:)\/title","value":"handlePanGestureForRightViewWithGesture:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1handlePanGestureForRightView(gesture:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handlePanGestureForRightViewWithGesture:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}