{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBInspectable"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftViewCoverBlurEffectWhenAlwaysVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBlurEffect","preciseIdentifier":"c:objc(cs)UIBlurEffect"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"返回值: 默认值:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"rootViewCoverBlurEffectForRightView"}]}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"注意:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"遮罩视图仅在左侧视图隐藏时可见，在显示\/隐藏状态之间具有动画效果。"}]}]}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/slsidemenu\/slsidemenu\/leftviewcoverblureffectwhenalwaysvisible"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/slsidemenu\/slsidemenu\/leftviewcoverblureffectwhenalwaysvisible"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/leftViewCoverBlurEffectWhenAlwaysVisible","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"使用此属性为左侧视图上方的遮罩视图设置 "},{"type":"codeVoice","code":"UIBlurEffect"},{"type":"text","text":"，"},{"type":"text","text":" "},{"type":"text","text":"仅当当前条件下的 "},{"type":"codeVoice","code":"leftViewAlwaysVisibleOptions"},{"type":"text","text":" 为 true 时可见。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftViewCoverBlurEffectWhenAlwaysVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBlurEffect","preciseIdentifier":"c:objc(cs)UIBlurEffect"},{"kind":"text","text":"?"}],"title":"leftViewCoverBlurEffectWhenAlwaysVisible","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SLSideMenu@objc(cs)SLSideMenu(py)leftViewCoverBlurEffectWhenAlwaysVisible","modules":[{"name":"SLSideMenu"}],"navigatorTitle":[{"kind":"identifier","text":"leftViewCoverBlurEffectWhenAlwaysVisible"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu"]]},"references":{"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu":{"role":"collection","title":"SLSideMenu","abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu/leftViewCoverBlurEffectWhenAlwaysVisible":{"role":"symbol","title":"leftViewCoverBlurEffectWhenAlwaysVisible","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftViewCoverBlurEffectWhenAlwaysVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBlurEffect","preciseIdentifier":"c:objc(cs)UIBlurEffect"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"使用此属性为左侧视图上方的遮罩视图设置 "},{"type":"codeVoice","code":"UIBlurEffect"},{"type":"text","text":"，"},{"type":"text","text":" "},{"type":"text","text":"仅当当前条件下的 "},{"type":"codeVoice","code":"leftViewAlwaysVisibleOptions"},{"type":"text","text":" 为 true 时可见。"}],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/leftViewCoverBlurEffectWhenAlwaysVisible","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leftViewCoverBlurEffectWhenAlwaysVisible"}],"url":"\/documentation\/slsidemenu\/slsidemenu\/leftviewcoverblureffectwhenalwaysvisible"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu":{"role":"symbol","title":"SLSideMenu","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenu"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenu"}],"url":"\/documentation\/slsidemenu\/slsidemenu"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"leftViewCoverBlurEffectWhenAlwaysVisible"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"leftViewCoverBlurEffectWhenAlwaysVisible"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIBlurEffect","preciseIdentifier":"c:objc(cs)UIBlurEffect"},{"kind":"text","text":" * "},{"kind":"identifier","text":"leftViewCoverBlurEffectWhenAlwaysVisible"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1leftViewCoverBlurEffectWhenAlwaysVisible\/title","value":"leftViewCoverBlurEffectWhenAlwaysVisible"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1leftViewCoverBlurEffectWhenAlwaysVisible\/fragments","value":[{"kind":"identifier","text":"leftViewCoverBlurEffectWhenAlwaysVisible"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/title","value":"SLSideMenu"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/fragments","value":[{"kind":"identifier","text":"SLSideMenu"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}