{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftViewBackgroundDecorationView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuBackgroundDecorationView","preciseIdentifier":"c:@M@SLSideMenu@objc(cs)SLSideMenuBackgroundDecorationView","text":"SLSideMenuBackgroundDecorationView"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/slsidemenu\/slsidemenu\/leftviewbackgrounddecorationview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/leftViewBackgroundDecorationView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"负责左视图的阴影、边框和背景的视图。"},{"type":"text","text":" "},{"type":"text","text":"通常不应该由用户访问。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftViewBackgroundDecorationView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SLSideMenuBackgroundDecorationView","preciseIdentifier":"c:@M@SLSideMenu@objc(cs)SLSideMenuBackgroundDecorationView"},{"kind":"text","text":"?"}],"title":"leftViewBackgroundDecorationView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:10SLSideMenuAAC028leftViewBackgroundDecorationD0AA0abefD0CSgvp","modules":[{"name":"SLSideMenu"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu"]]},"references":{"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu":{"role":"collection","title":"SLSideMenu","abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu/leftViewBackgroundDecorationView":{"role":"symbol","title":"leftViewBackgroundDecorationView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftViewBackgroundDecorationView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SLSideMenuBackgroundDecorationView","preciseIdentifier":"c:@M@SLSideMenu@objc(cs)SLSideMenuBackgroundDecorationView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"负责左视图的阴影、边框和背景的视图。"},{"type":"text","text":" "},{"type":"text","text":"通常不应该由用户访问。"}],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/leftViewBackgroundDecorationView","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu\/slsidemenu\/leftviewbackgrounddecorationview"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu":{"role":"symbol","title":"SLSideMenu","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenu"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenu"}],"url":"\/documentation\/slsidemenu\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuBackgroundDecorationView":{"role":"symbol","title":"SLSideMenuBackgroundDecorationView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenuBackgroundDecorationView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuBackgroundDecorationView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenuBackgroundDecorationView"}],"url":"\/documentation\/slsidemenu\/slsidemenubackgrounddecorationview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/title","value":"SLSideMenu"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/fragments","value":[{"kind":"identifier","text":"SLSideMenu"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuBackgroundDecorationView\/title","value":"SLSideMenuBackgroundDecorationView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuBackgroundDecorationView\/fragments","value":[{"kind":"identifier","text":"SLSideMenuBackgroundDecorationView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}