{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBInspectable"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightViewLayerBorderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"注意:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"仅与 "},{"type":"codeVoice","code":"rightViewLayerBorderWidth"},{"type":"text","text":" 一起使用时有意义。"}]}]}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/slsidemenu\/slsidemenu\/rightviewlayerbordercolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/slsidemenu\/slsidemenu\/rightviewlayerbordercolor"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/rightViewLayerBorderColor","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"使用此属性为右侧视图添加边框。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightViewLayerBorderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"title":"rightViewLayerBorderColor","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SLSideMenu@objc(cs)SLSideMenu(py)rightViewLayerBorderColor","modules":[{"name":"SLSideMenu"}],"navigatorTitle":[{"kind":"identifier","text":"rightViewLayerBorderColor"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu"]]},"references":{"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu":{"role":"symbol","title":"SLSideMenu","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenu"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenu"}],"url":"\/documentation\/slsidemenu\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu":{"role":"collection","title":"SLSideMenu","abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu/rightViewLayerBorderColor":{"role":"symbol","title":"rightViewLayerBorderColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightViewLayerBorderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"使用此属性为右侧视图添加边框。"}],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/rightViewLayerBorderColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rightViewLayerBorderColor"}],"url":"\/documentation\/slsidemenu\/slsidemenu\/rightviewlayerbordercolor"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"rightViewLayerBorderColor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"rightViewLayerBorderColor"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" * "},{"kind":"identifier","text":"rightViewLayerBorderColor"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/title","value":"SLSideMenu"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/fragments","value":[{"kind":"identifier","text":"SLSideMenu"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1rightViewLayerBorderColor\/title","value":"rightViewLayerBorderColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1rightViewLayerBorderColor\/fragments","value":[{"kind":"identifier","text":"rightViewLayerBorderColor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}