{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBInspectable"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootViewScaleWhenHiddenForLeftView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"返回：默认值："}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"如果已分配 "},{"type":"codeVoice","code":"rootViewScaleWhenHiddenForLeftView"},{"type":"text","text":"，则为 "},{"type":"codeVoice","code":"rootViewScaleWhenHiddenForLeftView"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"如果已分配 "},{"type":"codeVoice","code":"rootViewScaleWhenHidden"},{"type":"text","text":"，则为 "},{"type":"codeVoice","code":"rootViewScaleWhenHidden"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"如果 "},{"type":"codeVoice","code":"presentationStyle.shouldRootViewScale"},{"type":"text","text":" 为真，则为 "},{"type":"codeVoice","code":"0.8"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"否则为 "},{"type":"codeVoice","code":"1.0"}]}]}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/slsidemenu\/slsidemenu\/rootviewscalewhenhiddenforleftview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/slsidemenu\/slsidemenu\/rootviewscalewhenhiddenforleftview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/rootViewScaleWhenHiddenForLeftView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"使用此属性在根视图隐藏时设置缩放比例，仅当左侧视图显示时有效。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootViewScaleWhenHiddenForLeftView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"title":"rootViewScaleWhenHiddenForLeftView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SLSideMenu@objc(cs)SLSideMenu(py)rootViewScaleWhenHiddenForLeftView","modules":[{"name":"SLSideMenu"}],"navigatorTitle":[{"kind":"identifier","text":"rootViewScaleWhenHiddenForLeftView"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu"]]},"references":{"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu":{"role":"symbol","title":"SLSideMenu","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenu"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenu"}],"url":"\/documentation\/slsidemenu\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu":{"role":"collection","title":"SLSideMenu","abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu/rootViewScaleWhenHiddenForLeftView":{"role":"symbol","title":"rootViewScaleWhenHiddenForLeftView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootViewScaleWhenHiddenForLeftView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"使用此属性在根视图隐藏时设置缩放比例，仅当左侧视图显示时有效。"}],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/rootViewScaleWhenHiddenForLeftView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rootViewScaleWhenHiddenForLeftView"}],"url":"\/documentation\/slsidemenu\/slsidemenu\/rootviewscalewhenhiddenforleftview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"rootViewScaleWhenHiddenForLeftView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"rootViewScaleWhenHiddenForLeftView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootViewScaleWhenHiddenForLeftView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/title","value":"SLSideMenu"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/fragments","value":[{"kind":"identifier","text":"SLSideMenu"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1rootViewScaleWhenHiddenForLeftView\/title","value":"rootViewScaleWhenHiddenForLeftView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1rootViewScaleWhenHiddenForLeftView\/fragments","value":[{"kind":"identifier","text":"rootViewScaleWhenHiddenForLeftView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}