{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBInspectable"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootViewCoverBlurEffect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBlurEffect","preciseIdentifier":"c:objc(cs)UIBlurEffect"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"注意:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"遮罩视图仅在根视图隐藏时可见，在显示\/隐藏状态之间具有动画效果。"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"如果要隐藏根视图的内容或降低注意力，可以使用此属性。"}]}]}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/slsidemenu\/slsidemenu\/rootviewcoverblureffect"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/slsidemenu\/slsidemenu\/rootviewcoverblureffect"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/rootViewCoverBlurEffect","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"使用此属性为根视图上方的遮罩视图设置 "},{"type":"codeVoice","code":"UIBlurEffect"},{"type":"text","text":"。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootViewCoverBlurEffect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBlurEffect","preciseIdentifier":"c:objc(cs)UIBlurEffect"},{"kind":"text","text":"?"}],"title":"rootViewCoverBlurEffect","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SLSideMenu@objc(cs)SLSideMenu(py)rootViewCoverBlurEffect","modules":[{"name":"SLSideMenu"}],"navigatorTitle":[{"kind":"identifier","text":"rootViewCoverBlurEffect"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu"]]},"references":{"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu":{"role":"collection","title":"SLSideMenu","abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu/rootViewCoverBlurEffect":{"role":"symbol","title":"rootViewCoverBlurEffect","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootViewCoverBlurEffect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBlurEffect","preciseIdentifier":"c:objc(cs)UIBlurEffect"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"使用此属性为根视图上方的遮罩视图设置 "},{"type":"codeVoice","code":"UIBlurEffect"},{"type":"text","text":"。"}],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/rootViewCoverBlurEffect","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rootViewCoverBlurEffect"}],"url":"\/documentation\/slsidemenu\/slsidemenu\/rootviewcoverblureffect"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu":{"role":"symbol","title":"SLSideMenu","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenu"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenu"}],"url":"\/documentation\/slsidemenu\/slsidemenu"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"rootViewCoverBlurEffect"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"rootViewCoverBlurEffect"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIBlurEffect","preciseIdentifier":"c:objc(cs)UIBlurEffect"},{"kind":"text","text":" * "},{"kind":"identifier","text":"rootViewCoverBlurEffect"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1rootViewCoverBlurEffect\/title","value":"rootViewCoverBlurEffect"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1rootViewCoverBlurEffect\/fragments","value":[{"kind":"identifier","text":"rootViewCoverBlurEffect"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/title","value":"SLSideMenu"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/fragments","value":[{"kind":"identifier","text":"SLSideMenu"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}