{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootViewWrapperView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuWrapperView","preciseIdentifier":"c:@M@SLSideMenu@objc(cs)SLSideMenuWrapperView","text":"SLSideMenuWrapperView"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/slsidemenu\/slsidemenu\/rootviewwrapperview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/rootViewWrapperView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"包装用户提供的根视图的视图。"},{"type":"text","text":" "},{"type":"text","text":"通常不应该由用户访问。"},{"type":"text","text":" "},{"type":"text","text":"对于执行到新根视图的动画转换可能会有用。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootViewWrapperView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SLSideMenuWrapperView","preciseIdentifier":"c:@M@SLSideMenu@objc(cs)SLSideMenuWrapperView"},{"kind":"text","text":"?"}],"title":"rootViewWrapperView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:10SLSideMenuAAC015rootViewWrapperD0AA0abeD0CSgvp","modules":[{"name":"SLSideMenu"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu"]]},"references":{"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu":{"role":"symbol","title":"SLSideMenu","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenu"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenu"}],"url":"\/documentation\/slsidemenu\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuWrapperView":{"role":"symbol","title":"SLSideMenuWrapperView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenuWrapperView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuWrapperView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenuWrapperView"}],"url":"\/documentation\/slsidemenu\/slsidemenuwrapperview"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu/rootViewWrapperView":{"role":"symbol","title":"rootViewWrapperView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootViewWrapperView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SLSideMenuWrapperView","preciseIdentifier":"c:@M@SLSideMenu@objc(cs)SLSideMenuWrapperView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"包装用户提供的根视图的视图。"},{"type":"text","text":" "},{"type":"text","text":"通常不应该由用户访问。"},{"type":"text","text":" "},{"type":"text","text":"对于执行到新根视图的动画转换可能会有用。"}],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/rootViewWrapperView","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu\/slsidemenu\/rootviewwrapperview"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu":{"role":"collection","title":"SLSideMenu","abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/title","value":"SLSideMenu"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/fragments","value":[{"kind":"identifier","text":"SLSideMenu"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuWrapperView\/title","value":"SLSideMenuWrapperView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuWrapperView\/fragments","value":[{"kind":"identifier","text":"SLSideMenuWrapperView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}