{"variants":[{"paths":["\/documentation\/slsidemenu\/slsidemenu\/uigesturerecognizerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/slsidemenu\/slsidemenu\/uigesturerecognizerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/UIGestureRecognizerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/gestureRecognizer(_:shouldBeRequiredToFailBy:)","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/gestureRecognizer(_:shouldReceive:)","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"SLSideMenu"}],"role":"collectionGroup","title":"UIGestureRecognizerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu"]]},"references":{"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu/gestureRecognizer(_:shouldBeRequiredToFailBy:)":{"role":"symbol","title":"gestureRecognizer(_:shouldBeRequiredToFailBy:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldBeRequiredToFailBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/gestureRecognizer(_:shouldBeRequiredToFailBy:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gestureRecognizer:shouldBeRequiredToFailByGestureRecognizer:"}],"url":"\/documentation\/slsidemenu\/slsidemenu\/gesturerecognizer(_:shouldberequiredtofailby:)"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu":{"role":"collection","title":"SLSideMenu","abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu":{"role":"symbol","title":"SLSideMenu","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenu"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenu"}],"url":"\/documentation\/slsidemenu\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu/gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)":{"role":"symbol","title":"gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldRecognizeSimultaneouslyWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:"}],"url":"\/documentation\/slsidemenu\/slsidemenu\/gesturerecognizer(_:shouldrecognizesimultaneouslywith:)"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu/gestureRecognizer(_:shouldReceive:)":{"role":"symbol","title":"gestureRecognizer(_:shouldReceive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/gestureRecognizer(_:shouldReceive:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gestureRecognizer:shouldReceiveTouch:"}],"url":"\/documentation\/slsidemenu\/slsidemenu\/gesturerecognizer(_:shouldreceive:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/gestureRecognizer(_:shouldBeRequiredToFailBy:)","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/gestureRecognizer(_:shouldReceive:)","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1gestureRecognizer(_:shouldBeRequiredToFailBy:)\/title","value":"gestureRecognizer:shouldBeRequiredToFailByGestureRecognizer:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1gestureRecognizer(_:shouldBeRequiredToFailBy:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizer:shouldBeRequiredToFailByGestureRecognizer:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/title","value":"SLSideMenu"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/fragments","value":[{"kind":"identifier","text":"SLSideMenu"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)\/title","value":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1gestureRecognizer(_:shouldReceive:)\/title","value":"gestureRecognizer:shouldReceiveTouch:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1gestureRecognizer(_:shouldReceive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizer:shouldReceiveTouch:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}