{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenuWrapperView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/slsidemenu\/slsidemenuwrapperview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/slsidemenu\/slsidemenuwrapperview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.SLSideMenu\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)NSCoding","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)NSObject","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.SLSideMenu\/s7CVarArgP","doc:\/\/org.cocoapods.SLSideMenu\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SLSideMenu\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SLSideMenu\/SQ","doc:\/\/org.cocoapods.SLSideMenu\/SH","doc:\/\/org.cocoapods.SLSideMenu\/s8SendableP","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.SLSideMenu\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuWrapperView","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuWrapperView\/canLayoutSubviews"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuWrapperView\/layoutIfNeeded()","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuWrapperView\/layoutSublayers(of:)","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuWrapperView\/layoutSubviews()","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuWrapperView\/setNeedsLayout()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenuWrapperView"}],"title":"SLSideMenuWrapperView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SLSideMenu@objc(cs)SLSideMenuWrapperView","modules":[{"name":"SLSideMenu"}],"navigatorTitle":[{"kind":"identifier","text":"SLSideMenuWrapperView"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu"]]},"references":{"doc://org.cocoapods.SLSideMenu/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuWrapperView/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuWrapperView\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/slsidemenu\/slsidemenuwrapperview\/initwithcoder:"},"doc://org.cocoapods.SLSideMenu/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuWrapperView/canLayoutSubviews":{"role":"symbol","title":"canLayoutSubviews","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canLayoutSubviews"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuWrapperView\/canLayoutSubviews","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu\/slsidemenuwrapperview\/canlayoutsubviews"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuWrapperView/layoutSubviews()":{"role":"symbol","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuWrapperView\/layoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/slsidemenu\/slsidemenuwrapperview\/layoutsubviews()"},"doc://org.cocoapods.SLSideMenu/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuWrapperView/setNeedsLayout()":{"role":"symbol","title":"setNeedsLayout()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setNeedsLayout"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuWrapperView\/setNeedsLayout()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setNeedsLayout"}],"url":"\/documentation\/slsidemenu\/slsidemenuwrapperview\/setneedslayout()"},"doc://org.cocoapods.SLSideMenu/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuWrapperView/layoutSublayers(of:)":{"role":"symbol","title":"layoutSublayers(of:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSublayers"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CALayer","preciseIdentifier":"c:objc(cs)CALayer"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuWrapperView\/layoutSublayers(of:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSublayersOfLayer:"}],"url":"\/documentation\/slsidemenu\/slsidemenuwrapperview\/layoutsublayers(of:)"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuWrapperView":{"role":"symbol","title":"SLSideMenuWrapperView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenuWrapperView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuWrapperView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenuWrapperView"}],"url":"\/documentation\/slsidemenu\/slsidemenuwrapperview"},"doc://org.cocoapods.SLSideMenu/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIFocusItem"},"doc://org.cocoapods.SLSideMenu/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)NSObject"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu":{"role":"collection","title":"SLSideMenu","abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.SLSideMenu/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.SLSideMenu/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.SLSideMenu/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.SLSideMenu/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIAppearance"},"doc://org.cocoapods.SLSideMenu/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.SLSideMenu/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuWrapperView/initWithFrame:":{"role":"symbol","title":"initWithFrame:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuWrapperView\/initWithFrame:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/slsidemenu\/slsidemenuwrapperview\/initwithframe:"},"doc://org.cocoapods.SLSideMenu/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.SLSideMenu/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/s8SendableP"},"doc://org.cocoapods.SLSideMenu/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/SH"},"doc://org.cocoapods.SLSideMenu/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/5UIKit23UITraitChangeObservableP"},"doc://org.cocoapods.SLSideMenu/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.SLSideMenu/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.SLSideMenu/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)NSCoding"},"doc://org.cocoapods.SLSideMenu/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.SLSideMenu/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/s23CustomStringConvertibleP"},"doc://org.cocoapods.SLSideMenu/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/SQ"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuWrapperView/layoutIfNeeded()":{"role":"symbol","title":"layoutIfNeeded()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutIfNeeded"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuWrapperView\/layoutIfNeeded()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutIfNeeded"}],"url":"\/documentation\/slsidemenu\/slsidemenuwrapperview\/layoutifneeded()"},"doc://org.cocoapods.SLSideMenu/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.SLSideMenu/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(cs)UIView"},"doc://org.cocoapods.SLSideMenu/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SLSideMenuWrapperView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SLSideMenuWrapperView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SLSideMenuWrapperView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuWrapperView\/initWithCoder:","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuWrapperView\/initWithFrame:","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuWrapperView\/layoutIfNeeded()","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuWrapperView\/layoutSublayers(of:)","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuWrapperView\/layoutSubviews()","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuWrapperView\/setNeedsLayout()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.SLSideMenu\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenuWrapperView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuWrapperView~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuWrapperView~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuWrapperView~1setNeedsLayout()\/title","value":"setNeedsLayout"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuWrapperView~1setNeedsLayout()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setNeedsLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuWrapperView~1layoutSublayers(of:)\/title","value":"layoutSublayersOfLayer:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuWrapperView~1layoutSublayers(of:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSublayersOfLayer:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuWrapperView\/title","value":"SLSideMenuWrapperView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuWrapperView\/fragments","value":[{"kind":"identifier","text":"SLSideMenuWrapperView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuWrapperView~1layoutIfNeeded()\/title","value":"layoutIfNeeded"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuWrapperView~1layoutIfNeeded()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutIfNeeded"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}