{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenuBackgroundShadowView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/slsidemenu\/slsidemenubackgroundshadowview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/slsidemenu\/slsidemenubackgroundshadowview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.SLSideMenu\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)NSCoding","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)NSObject","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.SLSideMenu\/s7CVarArgP","doc:\/\/org.cocoapods.SLSideMenu\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SLSideMenu\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SLSideMenu\/SQ","doc:\/\/org.cocoapods.SLSideMenu\/SH","doc:\/\/org.cocoapods.SLSideMenu\/s8SendableP","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.SLSideMenu\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuBackgroundShadowView","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuBackgroundShadowView\/init()","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuBackgroundShadowView\/init(coder:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuBackgroundShadowView\/shadowBlur","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuBackgroundShadowView\/shadowColor"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuBackgroundShadowView\/draw(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenuBackgroundShadowView"}],"title":"SLSideMenuBackgroundShadowView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SLSideMenu@objc(cs)SLSideMenuBackgroundShadowView","modules":[{"name":"SLSideMenu"}],"navigatorTitle":[{"kind":"identifier","text":"SLSideMenuBackgroundShadowView"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu"]]},"references":{"doc://org.cocoapods.SLSideMenu/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.SLSideMenu/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.SLSideMenu/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(cs)UIView"},"doc://org.cocoapods.SLSideMenu/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.SLSideMenu/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIFocusItem"},"doc://org.cocoapods.SLSideMenu/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.SLSideMenu/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.SLSideMenu/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.SLSideMenu/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)NSCoding"},"doc://org.cocoapods.SLSideMenu/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.SLSideMenu/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/s7CVarArgP"},"doc://org.cocoapods.SLSideMenu/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.SLSideMenu/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.SLSideMenu/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.SLSideMenu/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)NSObject"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuBackgroundShadowView":{"role":"symbol","title":"SLSideMenuBackgroundShadowView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenuBackgroundShadowView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuBackgroundShadowView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenuBackgroundShadowView"}],"url":"\/documentation\/slsidemenu\/slsidemenubackgroundshadowview"},"doc://org.cocoapods.SLSideMenu/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/SQ"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuBackgroundShadowView/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuBackgroundShadowView\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/slsidemenu\/slsidemenubackgroundshadowview\/init()"},"doc://org.cocoapods.SLSideMenu/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.SLSideMenu/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuBackgroundShadowView/shadowBlur":{"role":"symbol","title":"shadowBlur","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shadowBlur"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuBackgroundShadowView\/shadowBlur","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu\/slsidemenubackgroundshadowview\/shadowblur"},"doc://org.cocoapods.SLSideMenu/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/SH"},"doc://org.cocoapods.SLSideMenu/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/s8SendableP"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuBackgroundShadowView/shadowColor":{"role":"symbol","title":"shadowColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shadowColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuBackgroundShadowView\/shadowColor","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu\/slsidemenubackgroundshadowview\/shadowcolor"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuBackgroundShadowView/draw(_:)":{"role":"symbol","title":"draw(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"draw"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuBackgroundShadowView\/draw(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"drawRect:"}],"url":"\/documentation\/slsidemenu\/slsidemenubackgroundshadowview\/draw(_:)"},"doc://org.cocoapods.SLSideMenu/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/s23CustomStringConvertibleP"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu":{"role":"collection","title":"SLSideMenu","abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.SLSideMenu/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.SLSideMenu/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.SLSideMenu/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)UIAppearance"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuBackgroundShadowView/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuBackgroundShadowView\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/slsidemenu\/slsidemenubackgroundshadowview\/init(coder:)"},"doc://org.cocoapods.SLSideMenu/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/5UIKit23UITraitChangeObservableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SLSideMenuBackgroundShadowView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SLSideMenuBackgroundShadowView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SLSideMenuBackgroundShadowView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuBackgroundShadowView\/draw(_:)","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuBackgroundShadowView\/init()","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuBackgroundShadowView\/init(coder:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.SLSideMenu\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenuBackgroundShadowView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuBackgroundShadowView\/title","value":"SLSideMenuBackgroundShadowView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuBackgroundShadowView\/fragments","value":[{"kind":"identifier","text":"SLSideMenuBackgroundShadowView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuBackgroundShadowView~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuBackgroundShadowView~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuBackgroundShadowView~1draw(_:)\/title","value":"drawRect:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuBackgroundShadowView~1draw(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"drawRect:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuBackgroundShadowView~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuBackgroundShadowView~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}