{"variants":[{"paths":["\/documentation\/slsidemenu"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/slsidemenu"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuBackgroundDecorationView","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuBackgroundShadowView","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuSegue","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuStatusBarBackgroundView","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuWrapperView"]},{"title":"Protocols","identifiers":["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuDelegate"]},{"title":"Extended Modules","identifiers":["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/UIKit"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"SLSideMenu","title":"SLSideMenu","symbolKind":"module","role":"collection","modules":[{"name":"SLSideMenu"}]},"hierarchy":{"paths":[[]]},"references":{"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/UIKit":{"role":"collection","title":"UIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/UIKit","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu\/uikit"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuWrapperView":{"role":"symbol","title":"SLSideMenuWrapperView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenuWrapperView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuWrapperView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenuWrapperView"}],"url":"\/documentation\/slsidemenu\/slsidemenuwrapperview"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuVersionString":{"role":"symbol","title":"SLSideMenuVersionString","fragments":[{"kind":"identifier","text":"SLSideMenuVersionString"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuVersionString","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu\/slsidemenuversionstring"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuBackgroundDecorationView":{"role":"symbol","title":"SLSideMenuBackgroundDecorationView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenuBackgroundDecorationView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuBackgroundDecorationView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenuBackgroundDecorationView"}],"url":"\/documentation\/slsidemenu\/slsidemenubackgrounddecorationview"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuDelegate":{"role":"symbol","title":"SLSideMenuDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenuDelegate"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenuDelegate"}],"url":"\/documentation\/slsidemenu\/slsidemenudelegate"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu":{"role":"collection","title":"SLSideMenu","abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuBackgroundShadowView":{"role":"symbol","title":"SLSideMenuBackgroundShadowView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenuBackgroundShadowView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuBackgroundShadowView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenuBackgroundShadowView"}],"url":"\/documentation\/slsidemenu\/slsidemenubackgroundshadowview"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuStatusBarBackgroundView":{"role":"symbol","title":"SLSideMenuStatusBarBackgroundView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenuStatusBarBackgroundView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuStatusBarBackgroundView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenuStatusBarBackgroundView"}],"url":"\/documentation\/slsidemenu\/slsidemenustatusbarbackgroundview"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu":{"role":"symbol","title":"SLSideMenu","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenu"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenu"}],"url":"\/documentation\/slsidemenu\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuVersionNumber":{"role":"symbol","title":"SLSideMenuVersionNumber","fragments":[{"kind":"identifier","text":"SLSideMenuVersionNumber"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu\/slsidemenuversionnumber"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuSegue":{"role":"symbol","title":"SLSideMenuSegue","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenuSegue"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuSegue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenuSegue"}],"url":"\/documentation\/slsidemenu\/slsidemenusegue"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuBackgroundDecorationView","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuBackgroundShadowView","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuSegue","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuStatusBarBackgroundView","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuWrapperView"]},{"title":"Variables","identifiers":["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuVersionNumber","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuWrapperView\/title","value":"SLSideMenuWrapperView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuWrapperView\/fragments","value":[{"kind":"identifier","text":"SLSideMenuWrapperView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuBackgroundDecorationView\/title","value":"SLSideMenuBackgroundDecorationView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuBackgroundDecorationView\/fragments","value":[{"kind":"identifier","text":"SLSideMenuBackgroundDecorationView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuBackgroundShadowView\/title","value":"SLSideMenuBackgroundShadowView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuBackgroundShadowView\/fragments","value":[{"kind":"identifier","text":"SLSideMenuBackgroundShadowView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuStatusBarBackgroundView\/title","value":"SLSideMenuStatusBarBackgroundView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuStatusBarBackgroundView\/fragments","value":[{"kind":"identifier","text":"SLSideMenuStatusBarBackgroundView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/title","value":"SLSideMenu"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/fragments","value":[{"kind":"identifier","text":"SLSideMenu"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuSegue\/title","value":"SLSideMenuSegue"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuSegue\/fragments","value":[{"kind":"identifier","text":"SLSideMenuSegue"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}