{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenuSegue"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/slsidemenu\/slsidemenusegue"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/slsidemenu\/slsidemenusegue"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.SLSideMenu\/objc(cs)UIStoryboardSegue"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)NSObject","doc:\/\/org.cocoapods.SLSideMenu\/s7CVarArgP","doc:\/\/org.cocoapods.SLSideMenu\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SLSideMenu\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SLSideMenu\/SQ","doc:\/\/org.cocoapods.SLSideMenu\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuSegue","interfaceLanguage":"swift"},"topicSections":[{"title":"Structures","identifiers":["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuSegue\/Identifier"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuSegue\/perform()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenuSegue"}],"title":"SLSideMenuSegue","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SLSideMenu@objc(cs)SLSideMenuSegue","modules":[{"name":"SLSideMenu"}],"navigatorTitle":[{"kind":"identifier","text":"SLSideMenuSegue"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu"]]},"references":{"doc://org.cocoapods.SLSideMenu/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/s23CustomStringConvertibleP"},"doc://org.cocoapods.SLSideMenu/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/SQ"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuSegue/perform()":{"role":"symbol","title":"perform()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"perform"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuSegue\/perform()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"perform"}],"url":"\/documentation\/slsidemenu\/slsidemenusegue\/perform()"},"doc://org.cocoapods.SLSideMenu/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/s7CVarArgP"},"doc://org.cocoapods.SLSideMenu/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/SH"},"doc://org.cocoapods.SLSideMenu/objc(cs)UIStoryboardSegue":{"type":"unresolvable","title":"UIStoryboardSegue","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(cs)UIStoryboardSegue"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuSegue/initWithIdentifier:source:destination:":{"role":"symbol","title":"initWithIdentifier:source:destination:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithIdentifier:source:destination:"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuSegue\/initWithIdentifier:source:destination:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithIdentifier:source:destination:"}],"url":"\/documentation\/slsidemenu\/slsidemenusegue\/initwithidentifier:source:destination:"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu":{"role":"collection","title":"SLSideMenu","abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuSegue":{"role":"symbol","title":"SLSideMenuSegue","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenuSegue"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuSegue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenuSegue"}],"url":"\/documentation\/slsidemenu\/slsidemenusegue"},"doc://org.cocoapods.SLSideMenu/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.SLSideMenu/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/objc(pl)NSObject"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuSegue/Identifier":{"role":"symbol","title":"SLSideMenuSegue.Identifier","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuSegue\/Identifier","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Identifier"}],"url":"\/documentation\/slsidemenu\/slsidemenusegue\/identifier"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SLSideMenuSegue"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SLSideMenuSegue"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SLSideMenuSegue"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuSegue\/initWithIdentifier:source:destination:","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuSegue\/perform()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.SLSideMenu\/objc(cs)UIStoryboardSegue"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenuSegue"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIStoryboardSegue","preciseIdentifier":"c:objc(cs)UIStoryboardSegue"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuSegue~1perform()\/title","value":"perform"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuSegue~1perform()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"perform"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuSegue\/title","value":"SLSideMenuSegue"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuSegue\/fragments","value":[{"kind":"identifier","text":"SLSideMenuSegue"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}