{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"gesture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldReceive"},{"kind":"text","text":" "},{"kind":"internalParam","text":"touch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/slsidemenu\/slsidemenu\/gesturerecognizer(_:shouldreceive:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/slsidemenu\/slsidemenu\/gesturerecognizer(_:shouldreceive:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/gestureRecognizer(_:shouldReceive:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIGestureRecognizerDelegate.gestureRecognizer(_:shouldReceive:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"gestureRecognizer:shouldReceiveTouch:"}],"role":"symbol","title":"gestureRecognizer(_:shouldReceive:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","externalID":"c:@CM@SLSideMenu@objc(cs)SLSideMenu(im)gestureRecognizer:shouldReceiveTouch:","extendedModule":"SLSideMenu","modules":[{"name":"SLSideMenu"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/UIGestureRecognizerDelegate-Implementations"]]},"references":{"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu":{"role":"collection","title":"SLSideMenu","abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu/gestureRecognizer(_:shouldReceive:)":{"role":"symbol","title":"gestureRecognizer(_:shouldReceive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/gestureRecognizer(_:shouldReceive:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gestureRecognizer:shouldReceiveTouch:"}],"url":"\/documentation\/slsidemenu\/slsidemenu\/gesturerecognizer(_:shouldreceive:)"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu/UIGestureRecognizerDelegate-Implementations":{"role":"collectionGroup","title":"UIGestureRecognizerDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/UIGestureRecognizerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/slsidemenu\/slsidemenu\/uigesturerecognizerdelegate-implementations"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu":{"role":"symbol","title":"SLSideMenu","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenu"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenu"}],"url":"\/documentation\/slsidemenu\/slsidemenu"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"gestureRecognizer:shouldReceiveTouch:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizer:shouldReceiveTouch:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"gestureRecognizer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"gesture"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldReceiveTouch:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"touch"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1gestureRecognizer(_:shouldReceive:)\/title","value":"gestureRecognizer:shouldReceiveTouch:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1gestureRecognizer(_:shouldReceive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizer:shouldReceiveTouch:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/title","value":"SLSideMenu"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/fragments","value":[{"kind":"identifier","text":"SLSideMenu"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}