{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBInspectable"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftViewOffsetWhenShowing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/slsidemenu\/slsidemenu\/leftviewoffsetwhenshowing"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/slsidemenu\/slsidemenu\/leftviewoffsetwhenshowing"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/leftViewOffsetWhenShowing","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"使用此属性来设置左侧视图在显示时的额外偏移。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftViewOffsetWhenShowing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"}],"title":"leftViewOffsetWhenShowing","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SLSideMenu@objc(cs)SLSideMenu(py)leftViewOffsetWhenShowing","modules":[{"name":"SLSideMenu"}],"navigatorTitle":[{"kind":"identifier","text":"leftViewOffsetWhenShowing"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu"]]},"references":{"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu":{"role":"collection","title":"SLSideMenu","abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu/leftViewOffsetWhenShowing":{"role":"symbol","title":"leftViewOffsetWhenShowing","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftViewOffsetWhenShowing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"}],"abstract":[{"type":"text","text":"使用此属性来设置左侧视图在显示时的额外偏移。"}],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/leftViewOffsetWhenShowing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leftViewOffsetWhenShowing"}],"url":"\/documentation\/slsidemenu\/slsidemenu\/leftviewoffsetwhenshowing"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu":{"role":"symbol","title":"SLSideMenu","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenu"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenu"}],"url":"\/documentation\/slsidemenu\/slsidemenu"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"leftViewOffsetWhenShowing"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"leftViewOffsetWhenShowing"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftViewOffsetWhenShowing"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1leftViewOffsetWhenShowing\/title","value":"leftViewOffsetWhenShowing"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1leftViewOffsetWhenShowing\/fragments","value":[{"kind":"identifier","text":"leftViewOffsetWhenShowing"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/title","value":"SLSideMenu"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/fragments","value":[{"kind":"identifier","text":"SLSideMenu"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}