{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftViewStatusBarBackgroundView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuStatusBarBackgroundView","preciseIdentifier":"c:@M@SLSideMenu@objc(cs)SLSideMenuStatusBarBackgroundView","text":"SLSideMenuStatusBarBackgroundView"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/slsidemenu\/slsidemenu\/leftviewstatusbarbackgroundview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/leftViewStatusBarBackgroundView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"位于状态栏正下方的视图，以避免用户内容与状态栏的干扰。"},{"type":"text","text":" "},{"type":"text","text":"负责状态栏的阴影、边框和背景。"},{"type":"text","text":" "},{"type":"text","text":"通常不应该由用户访问。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftViewStatusBarBackgroundView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SLSideMenuStatusBarBackgroundView","preciseIdentifier":"c:@M@SLSideMenu@objc(cs)SLSideMenuStatusBarBackgroundView"},{"kind":"text","text":"?"}],"title":"leftViewStatusBarBackgroundView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:10SLSideMenuAAC027leftViewStatusBarBackgroundD0AA0abefgD0CSgvp","modules":[{"name":"SLSideMenu"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu"]]},"references":{"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu":{"role":"collection","title":"SLSideMenu","abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuStatusBarBackgroundView":{"role":"symbol","title":"SLSideMenuStatusBarBackgroundView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenuStatusBarBackgroundView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuStatusBarBackgroundView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenuStatusBarBackgroundView"}],"url":"\/documentation\/slsidemenu\/slsidemenustatusbarbackgroundview"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu":{"role":"symbol","title":"SLSideMenu","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenu"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenu"}],"url":"\/documentation\/slsidemenu\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu/leftViewStatusBarBackgroundView":{"role":"symbol","title":"leftViewStatusBarBackgroundView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftViewStatusBarBackgroundView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SLSideMenuStatusBarBackgroundView","preciseIdentifier":"c:@M@SLSideMenu@objc(cs)SLSideMenuStatusBarBackgroundView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"位于状态栏正下方的视图，以避免用户内容与状态栏的干扰。"},{"type":"text","text":" "},{"type":"text","text":"负责状态栏的阴影、边框和背景。"},{"type":"text","text":" "},{"type":"text","text":"通常不应该由用户访问。"}],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/leftViewStatusBarBackgroundView","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu\/slsidemenu\/leftviewstatusbarbackgroundview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuStatusBarBackgroundView\/title","value":"SLSideMenuStatusBarBackgroundView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuStatusBarBackgroundView\/fragments","value":[{"kind":"identifier","text":"SLSideMenuStatusBarBackgroundView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/title","value":"SLSideMenu"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/fragments","value":[{"kind":"identifier","text":"SLSideMenu"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}