{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBInspectable"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftViewWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"返回值: 默认值:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"min(ScreenSize.minSide - 44.0, 320.0)"}]}]}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/slsidemenu\/slsidemenu\/leftviewwidth"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/slsidemenu\/slsidemenu\/leftviewwidth"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/leftViewWidth","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"用于确定左侧视图宽度的基本属性。"},{"type":"text","text":" "},{"type":"text","text":"用户可以分配值。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftViewWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"title":"leftViewWidth","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SLSideMenu@objc(cs)SLSideMenu(py)leftViewWidth","modules":[{"name":"SLSideMenu"}],"navigatorTitle":[{"kind":"identifier","text":"leftViewWidth"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu"]]},"references":{"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu":{"role":"collection","title":"SLSideMenu","abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu":{"role":"symbol","title":"SLSideMenu","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenu"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenu"}],"url":"\/documentation\/slsidemenu\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu/leftViewWidth":{"role":"symbol","title":"leftViewWidth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftViewWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"用于确定左侧视图宽度的基本属性。"},{"type":"text","text":" "},{"type":"text","text":"用户可以分配值。"}],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/leftViewWidth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leftViewWidth"}],"url":"\/documentation\/slsidemenu\/slsidemenu\/leftviewwidth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"leftViewWidth"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"leftViewWidth"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftViewWidth"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/title","value":"SLSideMenu"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/fragments","value":[{"kind":"identifier","text":"SLSideMenu"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1leftViewWidth\/title","value":"leftViewWidth"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1leftViewWidth\/fragments","value":[{"kind":"identifier","text":"leftViewWidth"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}