{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBInspectable"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightViewAnimationDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/slsidemenu\/slsidemenu\/rightviewanimationduration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/slsidemenu\/slsidemenu\/rightviewanimationduration"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/rightViewAnimationDuration","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"显示\/隐藏右侧视图的动画持续时间。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightViewAnimationDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"title":"rightViewAnimationDuration","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SLSideMenu@objc(cs)SLSideMenu(py)rightViewAnimationDuration","modules":[{"name":"SLSideMenu"}],"navigatorTitle":[{"kind":"identifier","text":"rightViewAnimationDuration"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu"]]},"references":{"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu":{"role":"collection","title":"SLSideMenu","abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu/rightViewAnimationDuration":{"role":"symbol","title":"rightViewAnimationDuration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightViewAnimationDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[{"type":"text","text":"显示\/隐藏右侧视图的动画持续时间。"}],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/rightViewAnimationDuration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rightViewAnimationDuration"}],"url":"\/documentation\/slsidemenu\/slsidemenu\/rightviewanimationduration"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu":{"role":"symbol","title":"SLSideMenu","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenu"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenu"}],"url":"\/documentation\/slsidemenu\/slsidemenu"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"rightViewAnimationDuration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"rightViewAnimationDuration"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightViewAnimationDuration"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1rightViewAnimationDuration\/title","value":"rightViewAnimationDuration"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1rightViewAnimationDuration\/fragments","value":[{"kind":"identifier","text":"rightViewAnimationDuration"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/title","value":"SLSideMenu"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/fragments","value":[{"kind":"identifier","text":"SLSideMenu"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}