{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBInspectable"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightViewBackgroundBlurEffect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBlurEffect","preciseIdentifier":"c:objc(cs)UIBlurEffect"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"返回值: 默认值："}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"如果 "},{"type":"codeVoice","code":"presentationStyle == .slideAboveBlurred"},{"type":"text","text":"，则为 "},{"type":"codeVoice","code":".regular"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"否则为 "},{"type":"codeVoice","code":"nil"}]}]}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/slsidemenu\/slsidemenu\/rightviewbackgroundblureffect"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/slsidemenu\/slsidemenu\/rightviewbackgroundblureffect"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/rightViewBackgroundBlurEffect","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"使用此属性设置位于右侧视图后面的背景视图的 "},{"type":"codeVoice","code":"UIBlurEffect"},{"type":"text","text":"。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightViewBackgroundBlurEffect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBlurEffect","preciseIdentifier":"c:objc(cs)UIBlurEffect"},{"kind":"text","text":"?"}],"title":"rightViewBackgroundBlurEffect","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SLSideMenu@objc(cs)SLSideMenu(py)rightViewBackgroundBlurEffect","modules":[{"name":"SLSideMenu"}],"navigatorTitle":[{"kind":"identifier","text":"rightViewBackgroundBlurEffect"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu"]]},"references":{"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu/rightViewBackgroundBlurEffect":{"role":"symbol","title":"rightViewBackgroundBlurEffect","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightViewBackgroundBlurEffect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBlurEffect","preciseIdentifier":"c:objc(cs)UIBlurEffect"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"使用此属性设置位于右侧视图后面的背景视图的 "},{"type":"codeVoice","code":"UIBlurEffect"},{"type":"text","text":"。"}],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/rightViewBackgroundBlurEffect","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rightViewBackgroundBlurEffect"}],"url":"\/documentation\/slsidemenu\/slsidemenu\/rightviewbackgroundblureffect"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu":{"role":"collection","title":"SLSideMenu","abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu":{"role":"symbol","title":"SLSideMenu","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenu"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenu"}],"url":"\/documentation\/slsidemenu\/slsidemenu"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"rightViewBackgroundBlurEffect"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"rightViewBackgroundBlurEffect"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIBlurEffect","preciseIdentifier":"c:objc(cs)UIBlurEffect"},{"kind":"text","text":" * "},{"kind":"identifier","text":"rightViewBackgroundBlurEffect"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1rightViewBackgroundBlurEffect\/title","value":"rightViewBackgroundBlurEffect"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1rightViewBackgroundBlurEffect\/fragments","value":[{"kind":"identifier","text":"rightViewBackgroundBlurEffect"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/title","value":"SLSideMenu"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/fragments","value":[{"kind":"identifier","text":"SLSideMenu"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}