{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightViewBackgroundShadowView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuBackgroundShadowView","preciseIdentifier":"c:@M@SLSideMenu@objc(cs)SLSideMenuBackgroundShadowView","text":"SLSideMenuBackgroundShadowView"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/slsidemenu\/slsidemenu\/rightviewbackgroundshadowview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/rightViewBackgroundShadowView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"负责右视图阴影的视图。位于"},{"type":"codeVoice","code":"rightViewBackgroundDecorationView"},{"type":"text","text":"内。"},{"type":"text","text":" "},{"type":"text","text":"通常不应该由用户访问。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightViewBackgroundShadowView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SLSideMenuBackgroundShadowView","preciseIdentifier":"c:@M@SLSideMenu@objc(cs)SLSideMenuBackgroundShadowView"},{"kind":"text","text":"?"}],"title":"rightViewBackgroundShadowView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:10SLSideMenuAAC025rightViewBackgroundShadowD0AA0abefD0CSgvp","modules":[{"name":"SLSideMenu"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu"]]},"references":{"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu":{"role":"symbol","title":"SLSideMenu","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenu"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenu"}],"url":"\/documentation\/slsidemenu\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu":{"role":"collection","title":"SLSideMenu","abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenuBackgroundShadowView":{"role":"symbol","title":"SLSideMenuBackgroundShadowView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenuBackgroundShadowView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenuBackgroundShadowView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenuBackgroundShadowView"}],"url":"\/documentation\/slsidemenu\/slsidemenubackgroundshadowview"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu/rightViewBackgroundShadowView":{"role":"symbol","title":"rightViewBackgroundShadowView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightViewBackgroundShadowView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SLSideMenuBackgroundShadowView","preciseIdentifier":"c:@M@SLSideMenu@objc(cs)SLSideMenuBackgroundShadowView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"负责右视图阴影的视图。位于"},{"type":"codeVoice","code":"rightViewBackgroundDecorationView"},{"type":"text","text":"内。"},{"type":"text","text":" "},{"type":"text","text":"通常不应该由用户访问。"}],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/rightViewBackgroundShadowView","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu\/slsidemenu\/rightviewbackgroundshadowview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/title","value":"SLSideMenu"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/fragments","value":[{"kind":"identifier","text":"SLSideMenu"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuBackgroundShadowView\/title","value":"SLSideMenuBackgroundShadowView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenuBackgroundShadowView\/fragments","value":[{"kind":"identifier","text":"SLSideMenuBackgroundShadowView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}