{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":" "},{"kind":"internalParam","text":"newCollection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"coordinator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewControllerTransitionCoordinator","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/slsidemenu\/slsidemenu\/willtransition(to:with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/slsidemenu\/slsidemenu\/willtransition(to:with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/willTransition(to:with:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"willTransitionToTraitCollection:withTransitionCoordinator:"}],"role":"symbol","title":"willTransition(to:with:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewControllerTransitionCoordinator","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@SLSideMenu@objc(cs)SLSideMenu(im)willTransitionToTraitCollection:withTransitionCoordinator:","extendedModule":"SLSideMenu","modules":[{"name":"SLSideMenu"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu"]]},"references":{"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu/willTransition(to:with:)":{"role":"symbol","title":"willTransition(to:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewControllerTransitionCoordinator","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu\/willTransition(to:with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"willTransitionToTraitCollection:withTransitionCoordinator:"}],"url":"\/documentation\/slsidemenu\/slsidemenu\/willtransition(to:with:)"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu":{"role":"collection","title":"SLSideMenu","abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu","kind":"symbol","type":"topic","url":"\/documentation\/slsidemenu"},"doc://org.cocoapods.SLSideMenu/documentation/SLSideMenu/SLSideMenu":{"role":"symbol","title":"SLSideMenu","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLSideMenu"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SLSideMenu\/documentation\/SLSideMenu\/SLSideMenu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLSideMenu"}],"url":"\/documentation\/slsidemenu\/slsidemenu"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"willTransitionToTraitCollection:withTransitionCoordinator:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willTransitionToTraitCollection:withTransitionCoordinator:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"willTransitionToTraitCollection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"newCollection"},{"kind":"text","text":" "},{"kind":"identifier","text":"withTransitionCoordinator:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<UIViewControllerTransitionCoordinator>","preciseIdentifier":"c:Qoobjc(pl)UIViewControllerTransitionCoordinator"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"coordinator"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1willTransition(to:with:)\/title","value":"willTransitionToTraitCollection:withTransitionCoordinator:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu~1willTransition(to:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willTransitionToTraitCollection:withTransitionCoordinator:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/title","value":"SLSideMenu"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SLSideMenu~1documentation~1SLSideMenu~1SLSideMenu\/fragments","value":[{"kind":"identifier","text":"SLSideMenu"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}